using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class MapManager : MonoBehaviour
{
    /*
     * The MapManager takes the dungeon generated by DungeonManager,
     * rendering a visual display of it on the GUI.
     */
    
    void Awake()
    {
        DungeonManager.DungeonGenerated += MapGenUpdate;
    }
    public void MapGenUpdate(MapTile[,] tiles, int size) // pass in tile list and size to render
    {  
        
    }
    


}
