using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class MapManager : MonoBehaviour
{
    public GameObject TilePrefab;
    private int tileOffset = 2;
    /*
     * The MapManager takes the dungeon generated by DungeonManager,
     * rendering a visual display of it.
     */
    public void MapGenUpdate(MapTile[,] tiles, int size) // pass in tile list and size to render
    {  
        for(int x = 0; x< size; x++){
            for(int y = 0; y< size; y++){
                Vector3 position = new Vector3 (x * tileOffset, 0, y * tileOffset);
                GameObject currTile = Instantiate(TilePrefab, position, Quaternion.identity);
                // Instantiate creates a copy of a prefab at the given location

            }
        }
    }
    


}
